# Generated by Django 2.2.2 on 2019-06-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('uid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('email1', models.CharField(max_length=50)),
                ('email2', models.CharField(max_length=50)),
                ('ra', models.IntegerField()),
                ('categoria', models.CharField(max_length=1)),
            ],
        ),
    ]
