# Generated by Django 2.2.2 on 2019-06-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResLabApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ra',
            field=models.CharField(max_length=10),
        ),
    ]
