# Generated by Django 2.2.2 on 2019-06-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResLabApp', '0003_usuario_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
