# Generated by Django 2.2.2 on 2019-06-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResLabApp', '0009_auto_20190629_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='tipo',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
