# Generated by Django 2.2.2 on 2019-06-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResLabApp', '0011_auto_20190629_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='diasemana',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
